import { describe, it, expect } from 'vitest'
import { writeFileSync, mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { parseClaudeSession } from './claude.js'
import { TOOL_RESULT_LIMIT } from './tool-calls.js'

function writeTmpSession(lines: Record<string, unknown>[]): string {
  const dir = mkdtempSync(join(tmpdir(), 'spool-test-'))
  const fp = join(dir, 'session.jsonl')
  writeFileSync(fp, lines.map(l => JSON.stringify(l)).join('\n'))
  return fp
}

const baseRecord = (overrides: Record<string, unknown>) => ({
  sessionId: 'test-uuid',
  cwd: '/tmp',
  timestamp: '2026-01-01T00:00:00Z',
  ...overrides,
})

describe('parseClaudeSession', () => {
  it('uses first user message as title by default', () => {
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'Help me fix the login bug' } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'Sure', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('Help me fix the login bug')
  })

  it('uses custom-title when present', () => {
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'Help me fix the login bug' } }),
      baseRecord({ type: 'custom-title', customTitle: 'login-bugfix' }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'Sure', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('login-bugfix')
  })

  it('uses last custom-title when renamed multiple times', () => {
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'Help me' } }),
      baseRecord({ type: 'custom-title', customTitle: 'first-name' }),
      baseRecord({ type: 'custom-title', customTitle: 'final-name' }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'Ok', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('final-name')
  })

  it('skips noise from local-command-caveat / command-name / command-args slash invocations and uses real query as title', () => {
    // Reproduces the exact head of an agent-search JSONL: Claude Code injects
    // a caveat block, then a /model slash-command (with command-args="default"),
    // before the actual user prompt. Without the strip rules the title was
    // "Caveat: The messages below..." (200 chars) and a stray "default" leaked
    // into the FTS index.
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>' } }),
      baseRecord({ type: 'user', uuid: 'u2', message: { role: 'user', content: '<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args>default</command-args>' } }),
      baseRecord({ type: 'user', uuid: 'u3', message: { role: 'user', content: '<local-command-stdout>Set model to claude-opus-4-7</local-command-stdout>' } }),
      baseRecord({ type: 'user', uuid: 'u4', message: { role: 'user', content: 'what did I do today?' } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'You did things.', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('what did I do today?')
    if (result?.kind === 'parsed') {
      const userTexts = result.session.messages.filter(m => m.role === 'user').map(m => m.contentText)
      expect(userTexts).toEqual(['what did I do today?'])
    }
  })

  it('preserves bare <command-args> content when not part of a slash-command triplet', () => {
    // If a user pastes log/code containing <command-args> outside the slash-
    // command triplet, the inner content must survive. Only the triplet form
    // (starting with <command-name>) gets stripped wholesale.
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'I saw <command-args>weird-payload</command-args> in the logs, what does it mean?' } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'It means...', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('I saw weird-payload in the logs, what does it mean?')
  })

  it('strips spool-system-prelude marker from user message and uses what follows as title', () => {
    // Reproduces what acp.ts buildPrompt sends: a prelude block wrapping the
    // system instructions, with the user's bare query at the end.
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: '<spool-system-prelude>\nYou have access to a local knowledge base...\nlong system body\n</spool-system-prelude>\n\nwhat did I do today?' } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'You did things.', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('what did I do today?')
  })

  it('strips marker tags when content is array-of-text-blocks (the actual ACP wire format)', () => {
    // Claude Code persists ACP prompt input as an array of content blocks:
    //   message.content = [{ type: 'text', text: '<spool-system-prelude>...' }]
    // The strip rules must apply to this shape, not just bare strings — this
    // is the form actually written to JSONL when Spool spawns Claude via ACP.
    const fp = writeTmpSession([
      baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: [
        { type: 'text', text: '<spool-system-prelude>\nlong system body\n</spool-system-prelude>\n\nwhat did I do today?' },
      ] } }),
      baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'ok', model: 'claude-opus-4-6' } }),
    ])
    const result = parseClaudeSession(fp)
    expect(result?.title).toBe('what did I do today?')
  })

  describe('tool calls and thinking', () => {
    it('captures tool_use input and pairs the tool_result from the following user record', () => {
      // Claude splits one invocation across two records: the assistant's
      // tool_use, then a user record carrying the matching tool_result.
      // The result must land on the assistant message that made the call.
      const fp = writeTmpSession([
        baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'list the files' } }),
        baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: [
          { type: 'tool_use', id: 'toolu_1', name: 'Bash', input: { command: 'ls', description: 'List files' } },
        ] } }),
        baseRecord({ type: 'user', uuid: 'u2', message: { role: 'user', content: [
          { type: 'tool_result', tool_use_id: 'toolu_1', content: 'a.txt\nb.txt' },
        ] } }),
      ])
      const result = parseClaudeSession(fp)
      const assistant = result?.messages.find(m => m.uuid === 'a1')
      expect(assistant?.toolNames).toEqual(['Bash'])
      expect(assistant?.toolCalls).toHaveLength(1)
      expect(assistant?.toolCalls?.[0]?.name).toBe('Bash')
      expect(assistant?.toolCalls?.[0]?.input).toContain('"command": "ls"')
      expect(assistant?.toolCalls?.[0]?.result).toBe('a.txt\nb.txt')
      expect(assistant?.toolCalls?.[0]?.isError).toBeUndefined()
    })

    it('marks a failed tool_result with isError', () => {
      const fp = writeTmpSession([
        baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'run it' } }),
        baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: [
          { type: 'tool_use', id: 'toolu_1', name: 'Bash', input: { command: 'nope' } },
        ] } }),
        baseRecord({ type: 'user', uuid: 'u2', message: { role: 'user', content: [
          { type: 'tool_result', tool_use_id: 'toolu_1', content: 'command not found', is_error: true },
        ] } }),
      ])
      const call = parseClaudeSession(fp)?.messages.find(m => m.uuid === 'a1')?.toolCalls?.[0]
      expect(call?.isError).toBe(true)
      expect(call?.result).toBe('command not found')
    })

    it('captures plaintext thinking and drops encrypted (empty) thinking blocks', () => {
      // Extended-thinking turns emit a thinking block whose text is empty
      // when the content is server-side encrypted — only `signature` is
      // present. Those must not produce an empty disclosure in the UI.
      const fp = writeTmpSession([
        baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'think about it' } }),
        baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: [
          { type: 'thinking', thinking: 'Let me consider the options.' },
          { type: 'text', text: 'Here is my answer.' },
        ] } }),
        baseRecord({ type: 'assistant', uuid: 'a2', message: { role: 'assistant', content: [
          { type: 'thinking', thinking: '', signature: 'CAIShQMK' },
          { type: 'text', text: 'Second answer.' },
        ] } }),
      ])
      const messages = parseClaudeSession(fp)?.messages ?? []
      expect(messages.find(m => m.uuid === 'a1')?.thinking).toBe('Let me consider the options.')
      expect(messages.find(m => m.uuid === 'a2')?.thinking).toBeUndefined()
    })

    it('keeps a thinking-only turn that would otherwise be dropped as empty', () => {
      // Pre-existing behaviour skips messages with no text and no tools.
      // A turn carrying only reasoning still has something to show.
      const fp = writeTmpSession([
        baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'hello' } }),
        baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: [
          { type: 'thinking', thinking: 'Reasoning with no visible reply.' },
        ] } }),
      ])
      const assistant = parseClaudeSession(fp)?.messages.find(m => m.uuid === 'a1')
      expect(assistant?.thinking).toBe('Reasoning with no visible reply.')
      expect(assistant?.contentText).toBe('')
    })

    it('does not strip XML-ish markup from tool result payloads', () => {
      // contentText runs through tag-stripping to keep the FTS index
      // clean. Tool output must bypass that — a Read of an HTML file
      // has to survive verbatim in the detail view.
      const fp = writeTmpSession([
        baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'read it' } }),
        baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: [
          { type: 'tool_use', id: 'toolu_1', name: 'Read', input: { file_path: '/tmp/x.html' } },
        ] } }),
        baseRecord({ type: 'user', uuid: 'u2', message: { role: 'user', content: [
          { type: 'tool_result', tool_use_id: 'toolu_1', content: [{ type: 'text', text: '<div>hi</div>' }] },
        ] } }),
      ])
      const call = parseClaudeSession(fp)?.messages.find(m => m.uuid === 'a1')?.toolCalls?.[0]
      expect(call?.result).toBe('<div>hi</div>')
    })

    it('clamps oversized tool results and flags the truncation', () => {
      // Tool output is unbounded (cat a log, read a large file). The
      // clamp is what keeps spool.db from ballooning for a detail view
      // that is collapsed by default.
      const huge = 'x'.repeat(TOOL_RESULT_LIMIT + 500)
      const fp = writeTmpSession([
        baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'cat it' } }),
        baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: [
          { type: 'tool_use', id: 'toolu_1', name: 'Bash', input: { command: 'cat big.log' } },
        ] } }),
        baseRecord({ type: 'user', uuid: 'u2', message: { role: 'user', content: [
          { type: 'tool_result', tool_use_id: 'toolu_1', content: huge },
        ] } }),
      ])
      const call = parseClaudeSession(fp)?.messages.find(m => m.uuid === 'a1')?.toolCalls?.[0]
      expect(call?.result).toHaveLength(TOOL_RESULT_LIMIT)
      expect(call?.resultTruncated).toBe(true)
    })

    it('leaves toolCalls undefined for ordinary text turns', () => {
      const fp = writeTmpSession([
        baseRecord({ type: 'user', uuid: 'u1', message: { role: 'user', content: 'hi' } }),
        baseRecord({ type: 'assistant', uuid: 'a1', message: { role: 'assistant', content: 'hello' } }),
      ])
      const assistant = parseClaudeSession(fp)?.messages.find(m => m.uuid === 'a1')
      expect(assistant?.toolCalls).toBeUndefined()
      expect(assistant?.thinking).toBeUndefined()
    })
  })
})
